CREATE TABLE IF NOT EXISTS core_locks (
    lock_id                         NUMBER                GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 10000 CONSTRAINT "CORE_LOCKS_NN_LOCK_ID" NOT NULL,
    object_owner                    VARCHAR2(32)          CONSTRAINT "CORE_LOCKS_NN_OBJECT_OWNER" NOT NULL,
    object_type                     VARCHAR2(32)          CONSTRAINT "CORE_LOCKS_NN_OBJECT_TYPE" NOT NULL,
    object_name                     VARCHAR2(128)         CONSTRAINT "CORE_LOCKS_NN_OBJECT_NAME" NOT NULL,
    locked_by                       VARCHAR2(128)         CONSTRAINT "CORE_LOCKS_NN_LOCKED_BY" NOT NULL,
    locked_at                       DATE                  CONSTRAINT "CORE_LOCKS_NN_LOCKED_AT" NOT NULL,
    expire_at                       DATE,
    counter                         NUMBER(4,0),
    object_payload                  CLOB,
    object_hash                     VARCHAR2(64),
    audit_trail                     VARCHAR2(128),
    --
    CONSTRAINT core_locks_pk
        PRIMARY KEY (lock_id)
);
--
COMMENT ON TABLE core_locks IS 'To track DDL events for objects locks';
--
COMMENT ON COLUMN core_locks.lock_id            IS '';
COMMENT ON COLUMN core_locks.object_owner       IS '';
COMMENT ON COLUMN core_locks.object_type        IS '';
COMMENT ON COLUMN core_locks.object_name        IS '';
COMMENT ON COLUMN core_locks.locked_by          IS '';
COMMENT ON COLUMN core_locks.locked_at          IS '';
COMMENT ON COLUMN core_locks.expire_at          IS '';
COMMENT ON COLUMN core_locks.counter            IS '';
COMMENT ON COLUMN core_locks.object_payload     IS '';
COMMENT ON COLUMN core_locks.object_hash        IS '';
COMMENT ON COLUMN core_locks.audit_trail        IS '';

